name: New Feature
description: An idea for a brand new feature, or a change to an existing one.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for your suggestion!

        We welcome any ideas about how to make the **NWBInspector** better for the community.

        Please keep in mind that new features may not get implemented immediately.
  - type: textarea
    id: summary
    attributes:
      label: Summary of Changes
      description: |
        What are you trying to achieve with the **NWBInspector**?

        Have you considered other ways of achieving this functionality? If so, can you summarize why you chose this approach?
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/.github/CODE_OF_CONDUCT.rst)
      options:
        - label: I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/.github/CODE_OF_CONDUCT.rst)
          required: true
        - label: Have you ensured this feature was not already [requested](https://github.com/neurodatawithoutborders/nwbinspector/issues)?
          required: true
