[tool.black]
line-length = 120
target-version = ['py37']
include = '\.pyi?$'
extend-exclude = '''
/(
  \.toml
  |\.yml
  |\.txt
  |\.sh
  |\.git
  |\.ini
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
)/
'''
force-exclude = '''
/(
   /*.txt
   /docs
   /docs/*
)\
'''

[tool.pydocstyle]
inherit = false
ignore = 'D401'  # D401='imperative mood'
match = '.*\.py'
convention = 'numpy'
