name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]

body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report!
- type: textarea
  id: what-happened
  attributes:
    label: What happened?
    description: Also tell us, what did you expect to happen?
    placeholder: Tell us what you see!
    value: "A bug happened!"
  validations:
    required: true
- type: textarea
  id: traceback
  attributes:
    label: Traceback
    description: Please copy and paste the traceback produced by the error. This may have been saved to the NWBInspector report under the section titled 'ERROR'.\n\n This section will be automatically formatted into code, so no need for backticks.
    render: shell
 - type: textarea
  id: versions
  attributes:
    label: Package Versions
    description: Please share your currently installed Python package versions by calling `pip freeze > environment_for_issue.txt` and uploading the text file along with this issue.\n\n If GitHub upload is not working, you can also copy & paste the output into this section (which is automatically formatted into code, so no need for backticks).
    render: shell
- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/.github/CODE_OF_CONDUCT.rst)
    options:
      - label: I agree to follow this project's Code of Conduct
        required: true
