name: black

on: push

jobs:
  flake8:
    runs-on: ubuntu-latest
    name: black
    steps:
      - name: Check out source
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: black
        uses: psf/black@stable
        with:
          args: ". --check"
