name: Daily workflows

on:
  schedule:
    - cron: "0 16 * * *"  # Daily at noon EST

jobs:

  run-daily-tests:
    uses: neurodatawithoutborders/nwbinspector/.github/workflows/testing.yml@dev

  run-daily-doc-link-checks:
    uses: neurodatawithoutborders/nwbinspector/.github/workflows/doc-link-checks.yml@dev

  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-send-mail@v3.7.1
        with:
          server_address: smtp.gmail.com
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: NWB Inspector Daily Failure
          to: ${{ secrets.DAILY_NOTIFICATION_EMAIL_LIST }}
          from: NWB Inspector
          body: "The daily workflow for the NWB Inspector failed: please check status at https://github.com/NeurodataWithoutBorders/nwbinspector/actions/workflows/dailies.yml"
          priority: high
