name: Streaming tests
on: workflow_call

jobs:
  build-and-test:
    name: Streaming tests using ${{ matrix.os }} with ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.8", "3.11"]
    steps:
      - uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: conda-forge
      - uses: actions/checkout@v3
      - run: git fetch --prune --unshallow --tags

      - name: Install pytest
        run: pip install pytest

      - name: Install package
        run: |
          pip install -e .
          pip install dandi

      - name: Run pytest on stream tests
        run: pytest tests/ -rsx tests/streaming_tests.py
