name: Testing Externl Links
on: pull_request
jobs:
  build-and-test:
    name: Testing External Links
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow --tags
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install sphinx deps
        run: pip install -r requirements-rtd.txt
      - name: Install package for API docs
        run: pip install -e .
      - name: Run pytest with coverage
        run: sphinx -b linkcheck ./docs ./test_build
